/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5fe55f2d-b85d-4080-9558-3daa893382de",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Ftek1sfgT",
    "aws_user_pools_web_client_id": "1gai9udfugv2u9u8t8gbgijt9",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://pgjvojnuandnjkfb3prhf4qzvq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "skincheck360images205534-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
